Add provider for OpenStreetMap, using OAuth 1.0a, for v3
hybridauth/hybridauth pull request #1094
Opened 2019-06-24 18:16 UTC by don-vip

| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          |
| Major: Breaking Change?  | No
| Minor: New Feature?      | Yes (for v3)

This PR re-adds the OpenStreetMap (OSM) provider that was added in v2 (#869) but was not ported to v3 yet.

I cherry-picked the old commits to preserve history and credit @jocelynj work instead of a copy/paste.

2019-06-30 20:13 UTC, jocelynj commented
@don-vip: you don't really need to keep my commits, but thanks anyway :)

2020-03-04 14:12 UTC, ApacheEx approved these changes
can you apply this remark and check if everything still works?

2020-03-04 14:12 UTC, ApacheEx commented on src/Provider/OpenStreetMap.php
> +        $response = new \SimpleXMLElement($response);
looks like we now can use `$data = new Data\Collection($response);`

because it supports xml response.

2020-03-04 14:13 UTC, ApacheEx requested changes
thank you a lot. Would be nice to check this one thing

2024-04-27 09:44 UTC, alexanderzatko commented
sorry, I did not notice this and created a Provider for OpenStreetMap in my own PR. That one is for OAuth 2 and was tested with the 3.11.0 version of hybridauth

2026-06-11 18:13 UTC, closed without merging