Add new provider for Azure AD
hybridauth/hybridauth pull request #1197
Opened 2020-08-31 19:34 UTC by adeshrd

| Q                        | A
| ------------------------ | ---
| Fixed Issues?            | 
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      | Yes 

Added Azure AD provider

2020-09-02 14:29 UTC, nightw0lv commented
i saw that too for those who have STD is best solution

2020-09-12 19:50 UTC, ApacheEx requested changes
Thanks for your PR....let's fix a few things...

2020-09-12 19:50 UTC, ApacheEx commented on src/Provider/AzureAD.php
> +            $data = base64_decode(str_pad(strtr($payload, '-_', '+/'), strlen($payload) % 4, '=', STR_PAD_RIGHT));
HA v3 has "firebase/php-jwt" as dependency, does it make sense to use it here instead of custom solution?

2020-09-12 19:50 UTC, ApacheEx commented on src/Provider/AzureAD.php
> +    protected function validateAccessTokenExchange($response)
all these php function docs are needed.

2020-09-12 19:50 UTC, ApacheEx commented on src/Provider/AzureAD.php
> +            'access_type' => 'offline'
comma for last element in array is must :)

2020-09-12 19:50 UTC, ApacheEx commented on src/Provider/AzureAD.php
> +    * {@inheritdoc}
let's fix style of comment, to be like:
```
/**
 *
 */
```

2020-09-12 19:50 UTC, ApacheEx commented on src/Provider/AzureAD.php
> + * AzureAD provider
dot at the then is must.

2020-09-21 18:46 UTC, ApacheEx commented on src/Provider/AzureAD.php
> +        $this->tokenRefreshParameters += [
there are some changes here, pls adapt https://github.com/hybridauth/hybridauth/pull/1220

2021-07-11 16:00 UTC, tozjerimiah commented
How long do we need to wait for this PR to be merged? The suggested fixes seem simple to me?

2022-11-11 14:47 UTC, brenoxavier commented
This provider is not required. Microsoft Graph met my needs with Active Directory. I think it would be nice to add this to the documentation.

2023-03-12 09:10 UTC, ApacheEx commented
Closing PR based on response from @brenoxavier. Thanks

2023-03-12 09:10 UTC, closed without merging